### ISSUE TITLE
{Suggestion} Error Caused by KeyboardInterrupt

### ISSUE THREAD

**Issue by valentineu0** [ysfchn/toasted#2]
## Suggestion Description
When you stop the program with the **CTRL + C** combination while executing the program, an error message is sent. The error message can be suppressed.

## Ways to Observe the Error
1. Run the program appropriately.
2. Stop the program with the **CTRL + C** combination.
3. Observe the error.

## Expected Behavior
Error-free closing when using the combination.

## Screenshot

![Ekran görüntüsü 2024-03-25 214614](https://github.com/ysfchn/toasted/assets/78941156/dafc8e4d-7fcf-429d-9569-3c9ae2a0f030)

**Comment by ysfchn** [comment]
Fixed with 1ed634088ade07e552ece2d69956cf3ea2a379f4.

To install latest changes made in source code:

```
python -m pip install --upgrade --force-reinstall https://github.com/ysfchn/toasted/archive/refs/heads/main.zip
```
